# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='canteens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='dishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sum_score', models.FloatField(default=0)),
                ('amount_scorer', models.IntegerField(default=0)),
                ('label', models.CharField(max_length=200)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canteen_model.canteens')),
            ],
        ),
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='NULL', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='remarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('content', models.TextField(default='')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canteen_model.canteens')),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canteen_model.dishes')),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('password', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('authority', models.CharField(choices=[('LEVEL0', 'Admin'), ('LEVEL1', 'ChiefManager'), ('LEVEL2', 'Manager'), ('LEVEL3', 'User')], max_length=20)),
                ('online', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='windows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=200)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canteen_model.canteens')),
                ('imgurl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canteen_model.images')),
            ],
        ),
        migrations.AddField(
            model_name='remarks',
            name='remarker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canteen_model.users'),
        ),
        migrations.AddField(
            model_name='remarks',
            name='wid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canteen_model.windows'),
        ),
        migrations.AddField(
            model_name='images',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canteen_model.users'),
        ),
        migrations.AddField(
            model_name='dishes',
            name='imgurl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canteen_model.images'),
        ),
        migrations.AddField(
            model_name='dishes',
            name='wid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canteen_model.windows'),
        ),
        migrations.AddField(
            model_name='canteens',
            name='imgurl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canteen_model.images'),
        ),
    ]
