# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_model', '0003_images_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='url',
        ),
    ]
